version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: facilit-kanban
      POSTGRES_USER: facilit
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - facilit_kanban_network

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - facilit_kanban_network

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/facilit-kanban
      SPRING_R2DBC_USERNAME: facilit
      SPRING_R2DBC_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/facilit-kanban
      SPRING_FLYWAY_USER: facilit
      SPRING_FLYWAY_PASSWORD: password
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    ports:
      - "8043:8043"
    networks:
      - facilit_kanban_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  facilit_kanban_network:
    driver: bridge