global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'facilit-kanban'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:8043']  # ou localhost:8043
    tls_config:
      insecure_skip_verify: true  # ignora certificado self-signed
