name: Spring Boot CI/CD with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE: neto10/facilit-kanban-app
  JAVA_VERSION: 17

jobs:
  build-and-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Maven settings.xml
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.REPO_USERNAME }}</username>
                <password>${{ secrets.REPO_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF  

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build e (Testes) Maven
        run: mvn clean install -B -DskipTests

      - name: Gerar JAR
        run: mvn package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}:latest
